version: '3.8'

services:
  dev-server:
    container_name: obsync-server
    volumes:
      - './server:/app/server/'
    ports:
      - 8000:8080
    env_file:
      - .env
    build:
      context: .
      target: dev
