services:
  test:
    volumes:
      - './configs:/app/configs/'
      - './server:/app/server/'
    env_file:
      - .env
    build:
      context: .
      target: test

  dev-server:
    container_name: obsync-server
    volumes:
      - './server:/app/server/'
    ports:
      - 8000:8080
    env_file:
      - .env
    build:
      context: .
      target: dev
