services:
  - type: web
    name: obsidian-node-sync-server
    env: node
    buildCommand: pnpm i && pnpm build:server
    startCommand: pnpm start:server
    # only build if anything in the server workspace changes
    # not the plugins
    buildFilter:
      paths:
        - server/**
      ignoredPaths:
        - server/db/*.db
        - server/db/migrations/**
        - plugin/**
        - configs/**
    disk:
      name: data
      mountPath: /data/
      sizeGB: 1
